#!/usr/bin/env bash
# =============================================================================
# Tanzen — Dev Environment Setup
#
# Reads credentials from a running cluster, ensures port-forwards are active,
# and writes server/.env so the API server can be started with `npm run dev`
# (or `bun run src/server/index.ts`) without any manual credential lookup.
#
# Usage:
#   ./infra/scripts/dev-env.sh [OPTIONS]
#
# Options:
#   --namespace NS     Target namespace (default: tanzen-dev)
#   --no-portforward   Skip port-forward management (assume already running)
#
# Prerequisites: kubectl on PATH, valid kubeconfig context pointing at the cluster.
# This script is idempotent: re-running it refreshes server/.env with the
# current cluster credentials.
#
# TLS NOTE: The API server runs on Bun, which replaces node-fetch with native
# fetch. Native fetch ignores custom HTTPS agents, so the k8s client library
# cannot apply rejectUnauthorized=false even when skipTLSVerify is set. To work
# around this reliably, all k8s API calls (Secrets, MCP servers) are routed
# through kubectl proxy, which terminates TLS locally and exposes plain HTTP on
# :8001. This means the dev server is never affected by cluster cert rotation.
# =============================================================================
set -euo pipefail

NAMESPACE="${TANZEN_NAMESPACE:-tanzen-dev}"
MANAGE_PF=true
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/server/.env"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --namespace)       NAMESPACE="$2"; shift 2 ;;
    --no-portforward)  MANAGE_PF=false; shift   ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

log()  { echo "[$(date -u +%H:%M:%S)] $*"; }
need() { for cmd in "$@"; do command -v "$cmd" &>/dev/null || { echo "ERROR: '$cmd' not on PATH"; exit 1; }; done; }

need kubectl

# ---------------------------------------------------------------------------
# Port-forwards
# ---------------------------------------------------------------------------
port_in_use() { lsof -i ":$1" -sTCP:LISTEN -t &>/dev/null; }

ensure_portforward() {
  local svc="$1" local_port="$2" remote_port="$3"
  if port_in_use "$local_port"; then
    log "Port $local_port already in use — skipping port-forward for $svc"
    return
  fi
  log "Starting port-forward: $svc :$local_port → :$remote_port"
  kubectl port-forward -n "$NAMESPACE" "svc/$svc" "${local_port}:${remote_port}" \
    </dev/null >/dev/null 2>&1 &
  disown
  # Give it a moment to bind
  local retries=0
  while ! port_in_use "$local_port" && (( retries < 10 )); do
    sleep 0.5
    (( retries++ ))
  done
  port_in_use "$local_port" || { echo "ERROR: port-forward for $svc failed to bind on $local_port"; exit 1; }
  log "Port-forward for $svc is ready on :$local_port"
}

ensure_kubectl_proxy() {
  local port=8001
  if port_in_use "$port"; then
    log "Port $port already in use — skipping kubectl proxy"
    return
  fi
  log "Starting kubectl proxy on :$port"
  kubectl proxy --port="$port" --accept-hosts='^127\.0\.0\.1$' \
    </dev/null >/dev/null 2>&1 &
  disown
  local retries=0
  while ! port_in_use "$port" && (( retries < 10 )); do
    sleep 0.5
    (( retries++ ))
  done
  port_in_use "$port" || { echo "ERROR: kubectl proxy failed to bind on $port"; exit 1; }
  log "kubectl proxy ready on :$port"
}

if $MANAGE_PF; then
  log "Checking port-forwards (namespace: $NAMESPACE)..."
  ensure_portforward tanzen-postgres-rw  5432 5432
  ensure_portforward seaweedfs-filer     8333 8333
  ensure_portforward tanzen-redis-master 6379 6379
  ensure_portforward tanzen-temporal-frontend 7233 7233
  ensure_kubectl_proxy
fi

# ---------------------------------------------------------------------------
# Read credentials from cluster secrets
# ---------------------------------------------------------------------------
log "Reading credentials from cluster secrets..."

decode() { kubectl get secret -n "$NAMESPACE" "$1" -o jsonpath="{.data.$2}" | base64 -d; }

DB_PASSWORD="$(decode tanzen-db-credentials password)"
DB_USER="$(decode tanzen-db-credentials username)"
S3_ACCESS_KEY="$(decode seaweedfs-s3-credentials access_key)"
S3_SECRET_KEY="$(decode seaweedfs-s3-credentials secret_key)"

# ---------------------------------------------------------------------------
# Write server/.env
# ---------------------------------------------------------------------------
log "Writing ${ENV_FILE}..."

cat > "$ENV_FILE" <<EOF
# Generated by infra/scripts/dev-env.sh — do not edit by hand.
# Re-run the script to refresh after cluster credential rotation.

# Postgres (port-forwarded from svc/tanzen-postgres-rw)
DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@localhost:5432/tanzen

# SeaweedFS S3 (port-forwarded from svc/seaweedfs-filer)
S3_ENDPOINT_URL=http://localhost:8333
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}

# Redis (port-forwarded from svc/tanzen-redis-master)
REDIS_URL=redis://localhost:6379/0

# Temporal (port-forwarded from svc/tanzen-temporal-frontend)
TEMPORAL_ADDRESS=localhost:7233
TEMPORAL_NAMESPACE=default

# kubectl proxy — routes all k8s API calls over plain HTTP on localhost so that
# Bun's native fetch (which ignores HTTPS agents) never touches cluster TLS.
# Secrets and MCP-server routes check this env var and use it when set.
KUBECTL_PROXY_URL=http://127.0.0.1:8001
EOF

log "server/.env written. Start the server with:"
log "  cd server && bun run dev"
